version: "3.7"

services:
  client:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages
      - ./src:/app/src
      - ./styles:/app/styles
    env_file:
      - ./.env
