import Head from 'next/head'
import { FunctionComponent } from 'react'
import Content from '../src/components/Content'
import Header from '../src/components/Header'
import Sidebar from '../src/components/Sidebar'

const Home: FunctionComponent = () => {
  return (
    <div>
      <Head>
        <title>Cartedo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="relative z-40 flex min-h-screen">
        <Sidebar />
        <Content />
      </div>

      <footer></footer>
    </div>
  )
}

export default Home
