import Head from 'next/head'
import { FunctionComponent } from 'react'

const Home: FunctionComponent = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button className="m-4 px-4 py-2 bg-blue-600 text-white rounded-lg outline-none focus:outline-none hover:bg-blue-700 focus:ring-2 focus:ring-offset-blue-200 focus:ring-offset-2">
          Click Me!
        </button>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
